version: '3'

services:
  db:
    image: postgres:latest
    environment:
      POSTGRES_DB: Dog_api_db
      POSTGRES_USER: DogApi_db_user
      POSTGRES_PASSWORD: 1234
    volumes:
      - postgres_data:/var/lib/postgresql/data

  web:
    restart: always
    build: .
    command: python3 manage.py runserver 0.0.0.0:8080
    volumes:
      - /Users/gmoney/Documents/DockerExersise/scripts:/webservices
      - .:/code
    ports:
      - "8080:8080"
    depends_on:
      - db

volumes:
  postgres_data:
  scripts: