version: '3'

services:
  web:
    restart: always
    build: .
    volumes:
      - /Users/gmoney/Documents/DockerExersise/scripts:/webservices
    command: python3 manage.py runserver 0.0.0.0:8080
    ports:
      - "8080:8080"

volumes:
  scripts: